### ISSUE TITLE
Rename project to match charter

### ISSUE THREAD

**Issue by kylef** [the-hypermedia-project/representor-python#3]
I'm happy to do this once #2 is merged and the remaining tests are fixed.

**Comment by honzajavorek** [comment]
Shouldn't this be an issue for https://github.com/the-hypermedia-project/representor-swift instead of https://github.com/the-hypermedia-project/hypermedia-resource-python ?

**Comment by kylef** [comment]
No, this repository should be renamed to representor-python (looks like someone has already renamed it).

The remaining task is to change all of the code-base to use the name representor. This is to sync up with the current state of the [charter](https://github.com/the-hypermedia-project/charter).

**Comment by smizell** [comment]
This has been done thanks to @kylef :+1:
