### ISSUE TITLE
One Last Version for PyPi

### ISSUE THREAD

**Issue by smizell** [the-hypermedia-project/representor-python#6]
@kylef has set up PR #4 to rename the module to `representor` instead of `HypermediaResource`. In light of this, I think we should do the following.
- [x] Merge #5
- [x] Bump the version
- [x] Update the README to say this is deprecated as a library
- [x] Create a tag
- [x] Merge #4 and update README again
- [x] Upload a new library named Representor to PyPi

Too complicated?

Thoughts? @honzajavorek @kylef

**Comment by honzajavorek** [comment]
What exactly is the intended result? Do we want to have two libraries uploaded to PyPI, one marked in its README that its deprecated and with link to the new one?

**Comment by honzajavorek** [comment]
I see PyPI has probably no support for builtin redirects: https://pypi.python.org/pypi/pbs

**Comment by kylef** [comment]
@honzajavorek Currently the library is called `hypermedia_resource` in PyPI. The new name for this library is `representor`. The plan is to update `hypermedia_resource` (as 0.2.0) stating it has been deprecated and people should move to the `representor`.

**Comment by honzajavorek** [comment]
That's what I thought. It was just not completely clear to me from the todo list whether I got it right. Thanks. I think this is correct approach.

**Comment by smizell** [comment]
@kylef @honzajavorek Done! In record time.

https://pypi.python.org/pypi/representor
